# Generated by Django 4.2 on 2023-04-19 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ENProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('category', models.CharField(choices=[('RW', 'Real-world project'), ('PS', 'Personal project'), ('CH', 'Coding challenge')], max_length=2, verbose_name='category')),
                ('stack', models.CharField(max_length=50, verbose_name='stack')),
                ('role', models.CharField(max_length=100, verbose_name='role')),
                ('info', models.TextField(verbose_name='info')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='image')),
                ('page_link', models.URLField(blank=True, null=True, verbose_name='page_link')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='github_link')),
                ('codepen_link', models.URLField(blank=True, null=True, verbose_name='codepen_link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
            ],
            options={
                'db_table': 'en_projects',
            },
        ),
    ]
